### ISSUE TITLE
Element ID 'main' should be 'root'

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/react-create-element#13]
This lesson contains two occurrences of `document.getElementById('main')` within `ReactDOM.render()`. Using `main` here results in the following error message:

```
invariant.js:44 Uncaught Error: _registerComponent(...): Target container is not a DOM element.
    at invariant (invariant.js:44)
    at Object._renderNewRootComponent (ReactMount.js:311)
    at Object._renderSubtreeIntoContainer (ReactMount.js:401)
    at Object.render (ReactMount.js:422)
    at Object.<anonymous> (index.js:23)
    at __webpack_require__ (bootstrap 1c40f2e…:555)
    at fn (bootstrap 1c40f2e…:86)
    at Object.<anonymous> (bootstrap 1c40f2e…:578)
    at __webpack_require__ (bootstrap 1c40f2e…:555)
    at bootstrap 1c40f2e…:578
```

Using `root` instead, as shown in other parts of the lesson, produces the desired results.

Pull request forthcoming.

@aturkewi

**Comment by RJFerguson** [comment]
Looking at it again this morning, there is a main tag inside the body element of the index.html file. Could the issue be that the <main> tag should be a <div> tag? I think what you're suggesting makes more sense because it is more inline with how the rest of the lessons are set up, but I'm just curious if maybe that's why the error is popping up.

**Comment by ivalentine** [comment]
`main` is a [valid HTML tag](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/main), so I don't think making it a `div` would change anything.

I do find it strange, though, that `main` does not work even though there is a `main` element (with an ID of `main`), yet `root` works despite the absence of a `root` tag anywhere in the document.

**Comment by Lukeghenco** [comment]
Thanks @RJFerguson and @ivalentine, so the issue here is the public folder index.html is what is loading the code. The old index.html in the root folder is doing nothing. @ivalentine PR fixed this. I will remove the root index.html file too.
