### ISSUE TITLE
create-react-app usage outdated

### ISSUE THREAD

**Issue by CharlieTLe** [learn-co-curriculum/react-create-element#18]
The create-react-app usage is not provided in the README.

**Comment by DanielSeehausen** [comment]
Hi there,

Would you mind providing a bit more detail about the issue? Things that are especially useful:

An expanded explanation of what's going on.
Steps to reproduce the issue.
Details about your environment.
What's your operating system? Which version?
Are you using the Learn IDE or a local development environment?
A stack trace of any errors.
Thanks! 💙
