### ISSUE TITLE
Can we build a "start" script to test out the code?

### ISSUE THREAD

**Issue by jjseymour** [learn-co-curriculum/react-create-element#2]
It would be nice to run a server and view the output

**Comment by AnnJohn** [comment]
looping @SophieDeBenedetto and @ipc103 in here. If you guys think that's fine and can do it, then totally fine by me. We don't have a contractor resource for this now.

**Comment by SophieDeBenedetto** [comment]
@AnnJohn @jjseymour not necessary to build a start script. Students can run python simple server to see the app in action. I'll add a line to the README to explain.

**Comment by SophieDeBenedetto** [comment]
closed with this commit d447a0b18f611f91eeb7ce3ea577f85c7507bc8a
