### ISSUE TITLE
no style sheet exists

### ISSUE THREAD

**Issue by meebenitez** [learn-co-curriculum/react-create-element#20]
I had to create a new style sheet to see the different colored li's.

**Comment by DanielSeehausen** [comment]
Hi there ,

Would you mind providing a bit more detail about the issue? Things that are especially useful:

An expanded explanation of what's going on.
Steps to reproduce the issue.
Details about your environment.
What's your operating system? Which version?
Are you using the Learn IDE or a local development environment?
A stack trace of any errors.
Thanks! 💙
