### ISSUE TITLE
External reference in this lab is broken

### ISSUE THREAD

**Issue by timothylevi** [learn-co-curriculum/react-create-element#21]
The reference to [Raw React](https://jamesknelson.com/learn-raw-react-no-jsx-flux-es6-webpack/) is broken and that page is no longer available on the web. There's [an archived copy on the Wayback Machine](https://web.archive.org/web/20171110070015/https://jamesknelson.com/learn-raw-react-no-jsx-flux-es6-webpack/), but even that resource is pointing to [a newer version](https://reactarmory.com/guides/learn-react-by-itself/react-basics).

**Comment by DanielSeehausen** [comment]
Link currently working -- perhaps it was temporarily down? Please let me know if this is not the case for you @timothylevi or if I should be looking for something else. Thank you!
