### ISSUE TITLE
Direction skipped, reading needs update.

### ISSUE THREAD

**Issue by yehudamakarov** [learn-co-curriculum/react-create-element#22]
after `npm install -g create-react-app webpack` which installs the packages, make it clear that we make our own directory with `create-react-app <diretory-name>` or we are supposed to be forking the learn repo and using that.

Because the lab continues We will be running our mini-React application using npm. From the directory of this project, in your terminal, run: `npm install && npm start`. What is "this project referring to? Either we needed to fork/clone the repo or make our own directory or either.

:)

**Comment by DanielSeehausen** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
