### ISSUE TITLE
Not sure if this was meant as a readme or a codealong.

### ISSUE THREAD

**Issue by pickledyamsman** [learn-co-curriculum/react-create-element#3]
There is only one test that just checks if it runs which it does so that leads me to think this is a readme.

If it is a codealong, the scripts for index.html are already included in the file so they either shouldn't be in the file or the instructions to add them shouldn't be there.

The code in index.js (ReactDOM.render(list, document.getElementById('main'));) won't run if you follow along with the lesson because it conflicts with the other render.

If you modify container to include it like:
const container = React.createElement('div', {}, [title, paragraph, list])

and remove the first render it will then work but the classes don't add anything to the li elements as the lesson says it will.

**Comment by pickledyamsman** [comment]
cc @aturkewi @AnnJohn

**Comment by AnnJohn** [comment]
should also be a Readme. Learn is being a bit weird with this so I just removed the test folder altogether
