### ISSUE TITLE
Lesson should be codealong, not lab

### ISSUE THREAD

**Issue by ivalentine** [learn-co-curriculum/react-create-element#7]
This lesson shows up as a lab on Learn, which results in the wrong checkboxes appearing on the right hand side. This means that students are unable to properly complete this lab, and must skip it by clicking the gray "Next lesson" button.

This lesson does have an `index.js` file, but does not have any tests. Therefore, it should be classified as a codealong.

Affected tracks:
`v-000`

cc @aturkewi

**Comment by aturkewi** [comment]
Should be all set now :) Thanks!
